### ISSUE TITLE
close connection, close pool

### ISSUE THREAD

**Issue by ingoogni** [zhouyl/ConnectionPool#1]
Two related requests. 
Is it possible to add a way of closing a connection on _destroy?
Is it possible to provide a way to close all connections in the pool?

I use the pool for FTP connections and they like to be closed (ftp.quit())

```
import ftplib

class FTPpool(ConnectionPool):

  def _destroy(self, wrapped):
    '''销毁一个连接'''
    print(wrapped.connection.quit()) #ugly hack, added to close ftp conn
    self._unwrapper(wrapped)
    self._size -= 1

  def close(self):                   #ugly hack to close the pool
    _ids = [_id for _id, _ in self._ConnectionPool__wrappers.items()]
    for _id in _ids:
      self._destroy(self._ConnectionPool__wrappers[_id])


def ftp_conn(host,port)
  ftp = ftplib.FTP()
  ftp.connect(host, port)
  ftp.login()


pool = FTPpool(
    create=lambda: ftp_conn('127.0.0.1', 4242),
    max_size=10,
    max_usage=10,
    idle=60,
    ttl=60
)
```

**Comment by jmeppley** [comment]
I added a close callback in my [fork](https://github.com/jmeppley/ConnectionPool).

I'd be open to a close-all option, but I haven't thought about it.

**Comment by zhouyl** [comment]
> I added a close callback in my [fork](https://github.com/jmeppley/ConnectionPool).
> 
> I'd be open to a close-all option, but I haven't thought about it.

thanks for your contribution
