### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by jmeppley** [zhouyl/ConnectionPool#4]
I wanted to create an official conda package on conda-forge with the contents of my PR (#3). I'd like to use the same name you used on pip for continuity, but only if it's OK with you. I can build it from my fork or from yours if you accept the PR.

For reference, you can see the discussion here: https://github.com/conda-forge/staged-recipes/pull/12676

**Comment by zhouyl** [comment]
no problem, it's my pleasure
